### PR TITLE
made changes to README file

### PR DESCRIPTION
**Pull request by namraschazil**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by YMakushenko — CHANGES_REQUESTED** [review]
Could you please provide the data in the Column Orientation format?
Reason:
 - Most data analysis tools and libraries (like pandas in Python, Excel, or SQL databases) expect data in a format where each column represents a different variable and each row represents a different record.
- This format allows for more straightforward data manipulation, filtering, and analysis.

**Review by rktakk — APPROVED** [review]
approving to remove file

**Review by rktakk — APPROVED** [review]
approving - this data is in rows.

**Review by rktakk — CHANGES_REQUESTED** [review]
please upload changes from your own branch.

**Comment by rktakk** [comment]
batch approval - test purposes

**Comment by gwmchung** [comment]
Approved changes.

**Review by gwmchung — APPROVED** [review]

**Pull request closed without merging**
