### PR TITLE
Additional analysis

### PR DESCRIPTION
**Pull request by YMakushenko**
This PR introduces additional analyses related to the project data and population growth metrics:

1. Added dataset for Canada
2. Added an additional analysis: histograms, correlation matrix

Reviewer Notes:
Please review the data script for any potential optimizations.
Check the analysis.

Files Changed:
Additional_analysis.ipynb: Added tables, histogram and correlation matrix. **reports folder**
Canada.csv: Added csv file with dataset for Canada. **data/sql folder**

### CODE REVIEW

**Comment by rktakk** [comment]
1. The histograms and correlation matrix both look great.
2. If the sex ratio at birth (male births per female births) is going to be included, then female births per male births should also be included if it exists in the dataset.

**Comment by YMakushenko** [comment]
> 1. The histograms and correlation matrix both look great.
> 2. If the sex ratio at birth (male births per female births) is going to be included, then female births per male births should also be included if it exists in the dataset.

@rktakk 2. No, it doesn't exist in the dataset. It's easy to calculate, but I don't see the need for it. In any case, we can leave all further analyses to the Part 2 of the team project.

**Comment by namraschazil** [comment]
the histogram and correlation matrix look good. i have a question: is the sex ration at birth and life expectancy additional variables explored within the independant variable fertility rate? or is it a new relationship with the population growth?

**Comment by YMakushenko** [comment]
> the histogram and correlation matrix look good. i have a question: is the sex ration at birth and life expectancy additional variables explored within the independant variable fertility rate? or is it a new relationship with the population growth?

@namraschazil No, I didn't use the sex ration at birth and life expectancy within the independent variable fertility rate. I only additionally showed them on the histogram and correlation matrix to visualize the possible correlation and the possibility to use it in our further analysis (e.g. in Part 2 of the team project).

**Pull request merged**
